In [2]:
import numpy as np

# Question1: Create a null vector of size 10

In [3]:
null_vector=np.zeros(10)
print(null_vector)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


# Question2: Create a vector with values ranging from 10 to 49

In [4]:
vector=np.arange(10,50)
vector

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

# Question3: Reverse a vector (first element becomes last)

In [5]:
vector=np.arange(10,50)
reversed_vector=vector[::-1]
reversed_vector

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

# Question4: Create a 3x3 matrix with values ranging from 0 to 8

In [6]:
matrix=np.arange(9).reshape(3,3)
matrix

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

# Question5: Find indices of non-zero elements from [1,2,0,0,4,0]

In [7]:
arr = np.array([1, 2, 0, 0, 4, 0])
non_zero_values=arr[arr!=0]
non_zero_values


array([1, 2, 4])

# Question6: Create a 10x10 array with random values and find the minimum, maximum and mean values   

In [8]:
arr=np.random.rand(10,10)
min_value=np.min(arr)
max_value=np.max(arr)
mean_value=np.mean(arr)
print(min_value,
max_value,
mean_value)

0.019611376473492648 0.9892405020247192 0.5383235740566006


# Question7: What is the result of the following expressions?


  

In [9]:
print(0 * np.nan)  
print(np.nan == np.nan)   
print(np.inf > np.nan)  
print(np.nan - np.nan)   
print(np.nan in set([np.nan]))   
print(0.3 == 3*0.1) 

nan
False
False
nan
True
False


# Question8: Write a NumPy program to convert a list and tuple into arrays.

List to array: [1 2 3 4 5 6 7 8]   
Tuples to array: ((8, 4), (6,1), (2, 3))

In [10]:
list_data=[1,2,3,4,5,6,7,8]
tuple_data=((8,4),(6,1),(2,3))
list_array=np.array(list_data)
tuple_array=np.array(tuple_data)
print("List to array:\n", list_array)
print("Tuples to array:\n", tuple_array)

List to array:
 [1 2 3 4 5 6 7 8]
Tuples to array:
 [[8 4]
 [6 1]
 [2 3]]


# Question9: Write a NumPy program to append values to the end of an array. 
original array: [10, 20, 30] After append values to the end of the array: [10 20 30 40 50 60 70 80 90] 

In [11]:
original_array = np.array([10, 20, 30])
values_to_append = [40, 50, 60, 70, 80, 90]
new_array = np.append(original_array, values_to_append)
print("Original array:\n", original_array)
print("After append values to the end of the array:\n", new_array)

Original array:
 [10 20 30]
After append values to the end of the array:
 [10 20 30 40 50 60 70 80 90]


# Question10: How to add a border (filled with O's) around an existing array? 

In [12]:
array = np.ones((3, 3))
bordered_array = np.pad(array, pad_width=1, mode='constant', constant_values=0)
print(bordered_array)

[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


## Question11: Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [13]:
shape = (6, 7, 8)
index=np.unravel_index(100,shape)
print(index)

(1, 5, 4)


## Question12: Normalize a 5x5 random matrix

In [16]:
matrix = np.random.rand(5, 5)
mean_val = np.mean(matrix)
std_dev = np.std(matrix)
standardized_matrix = (matrix - mean_val) / std_dev
print(standardized_matrix)

[[-1.04617132 -1.140633   -0.57722581 -0.13975676  1.41670802]
 [-0.70206576  0.28272737 -0.1252178  -0.42004883  1.82598922]
 [-0.44638905  0.93706715 -1.26488507 -0.35138268  1.80643016]
 [ 1.74086806 -0.14502409  0.80064755 -0.78862838 -0.61895029]
 [-0.94726742  0.20941395 -1.18391965 -0.71348983  1.59120427]]


## Question13: Given a 1D array, negate all elements which are between 3 and 8, in place

In [17]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
arr[(arr >= 3) & (arr <= 8)] *= -1
arr

array([ 0,  1,  2, -3, -4, -5, -6, -7, -8,  9, 10])

# Question14: How to find common values between two arrays?

In [18]:
arr1 = np.array([3, 7, 2, 8, 4, 2, 5, 9, 7, 4])
arr2 = np.array([9, 4, 3, 8, 4])
intersected_values=np.intersect1d(arr1,arr2)
print(intersected_values)

[3 4 8 9]


## Question15: Write a NumPy program to test whether each element of a 1-D array is also present in a second array.


Array1: [0 10 20 40 60]   
Array2: [0, 40]


In [19]:
array1 = np.array([0, 10, 20, 40, 60])
array2 = np.array([0, 40])
res=np.isin(array1,array2)
print(res)

[ True False False  True False]


## Question16: How to get all the dates corresponding to the month of July 2016?

In [21]:
july_2016 = np.arange('2016-07','2016-08',dtype='datetime64[D]')
print(july_2016)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


## Question17: Extract the integer part of a random array using 5 different methods

In [23]:
arr = np.random.uniform(-10, 10, 5)  
method1 = np.trunc(arr)
method2 = np.floor(arr)
method3=np.ceil(arr)
method4=arr.astype(int)
method5=np.round(arr)
print(method1,method2,method3,method4,method5)

[-8.  3. -2. -5. -5.] [-9.  3. -3. -6. -6.] [-8.  4. -2. -5. -5.] [-8  3 -2 -5 -5] [-9.  3. -2. -6. -6.]


## Question18: Consider two random array A and B, check if they are equal  

In [25]:
A = np.random.randint(0, 10, 5)  
B = np.random.randint(0, 10, 5)  
equal_exact = np.array_equal(A, B)
equal_close=np.allclose(A,B)
print(A)
print(B)
print(equal_exact)
print(equal_close)

[6 8 3 4 4]
[7 5 4 8 5]
False
False


## Question19: How to find the closest value (to a given scalar) in a vector?

In [26]:
vector = np.arange(100)
scalar = np.random.uniform(0, 100)
closest_value = vector[np.abs(vector - scalar).argmin()]
print(vector)
print(scalar)
print(closest_value)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]
27.857846646995053
28


## Question20: Find the nearest value from a given value in an array

In [27]:
array = np.random.rand(10,10)
target_value = 0.5
nearest_value = array.flat[np.abs(array - target_value).argmin()]
print(array)
print(nearest_value)

[[7.94832811e-01 1.06372951e-01 7.57402596e-01 2.75701170e-01
  2.63885979e-01 4.96528058e-01 9.92899219e-01 9.42210428e-01
  9.34018503e-01 3.16103789e-01]
 [4.99125755e-02 6.35205118e-01 9.17755494e-01 8.40949150e-01
  8.10184307e-01 9.05352073e-01 7.38282229e-01 8.10558127e-01
  5.75870180e-01 1.82928957e-01]
 [3.20683542e-01 8.54503842e-01 5.54444293e-01 2.28115436e-02
  8.83464101e-01 5.06673598e-01 2.43107797e-01 1.19664881e-01
  1.12448618e-01 8.19297011e-02]
 [3.55495194e-01 4.70952558e-01 3.28351222e-01 5.51050756e-01
  4.51152119e-02 5.11285659e-01 5.30877313e-01 7.74879591e-01
  1.84029658e-01 7.69293492e-01]
 [4.02198294e-01 2.86188114e-01 7.77528655e-01 5.11611999e-01
  1.86951923e-02 9.11287597e-02 5.75030321e-01 4.67359526e-01
  3.94548734e-01 6.57914251e-01]
 [4.15168759e-01 7.16188526e-01 7.10282736e-01 8.53201875e-01
  6.62106830e-01 4.61706192e-01 6.07381741e-01 4.72620526e-01
  2.23411414e-01 4.48625807e-01]
 [6.79296025e-01 2.78277258e-01 2.85999212e-01 8.48828389e